services:
  code-server:
    image: linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago                                  # Change this
      - PASSWORD=<password>                                 # Optional
        #- HASHED_PASSWORD=                                 # Optional
      - SUDO_PASSWORD=<sudo-password>                       # Optional
        #- SUDO_PASSWORD_HASH=                              # Optional
        #- PROXY_DOMAIN=code-server.my.domain               # Optional
    volumes:
      # Mount additional volumes here
      - /home/pi/code-server/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
