services:
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    restart: always
    ports:
      - 80:80                                                  # Change this
    environment:
      DB_TYPE: sqlite
      DEFAULT_EMAIL: <user-email>                              # Change this
      DEFAULT_PASSWORD: <user-password>                        # Change this
      TOKEN_TIME: 3
      TZ: America/Chicago                                      # Change this
    volumes:
      - /mnt/nfs-share/Recipe_Book/data:/app/data              # Change this
