services:
  server:
    image: gitea/gitea:1.15.0
    container_name: gitea_app
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=<secure-password>                                   # Change this             
    restart: always
    networks:
      - gitea
    volumes:
      - /mnt/nfs-share/Gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
       - "3000:3000"                                                                # Change the ports before ':' if already allocated
       - "22:22"
    depends_on:
      - db

  db:
    image: arm64v8/mariadb:10.5
    container_name: gitea_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=<secure-root-password>                                  # Change this
      - MYSQL_USER=gitea 
      - MYSQL_PASSWORD=<secure-password>                                            # Change this
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  gitea:
    external: false
