services: 
    surfshark:
        # Image from https://github.com/ilteoood/docker-surfshark
        image: ilteoood/docker-surfshark
        container_name: surfshark
        environment: 
            # Get your credentials from https://my.surfshark.com/vpn/manual-setup/main
            - SURFSHARK_USER=<surfshark-user>                            # Change this
            - SURFSHARK_PASSWORD=<surfshark-pass>                        # Change this
            # Get the closest location server from https://my.surfshark.com/vpn/manual-setup/main
            - SURFSHARK_COUNTRY=can                                      # Change this
            - SURFSHARK_CITY=tor                                         # Change this
            - CONNECTION_TYPE=udp
            - LAN_NETWORK=192.168.1.0/24      #Optional - Need to specify subnet to access containers WebUI
        cap_add: 
            - NET_ADMIN
        devices:
            - /dev/net/tun
        ports:
            # We open the ports here, as this container will be the access point for the others
            # 192.168.1.XX = Host machine's LAN IP  
            - 192.168.1.XX:9091:9091 # Transmission_VPN
            - 192.168.1.XX:3002:3002 # Flood
            - 192.168.1.XX:9696:9696 # Prowlarr
            - 192.168.1.XX:8989:8989 # Sonarr 
            - 192.168.1.XX:7878:7878 # Radarr
            - 192.168.1.XX:8787:8787 # Readarr
            - 192.168.1.XX:8686:8686 # Lidarr
            - 192.168.1.XX:6767:6767 # Bazarr
        restart: unless-stopped
        dns:
            - 1.1.1.1
    
    # Container to test the external IP of the containers
    # Alternatively, the external IP can be found by running `curl ifconfig.me` from within the container
    #service_test:
    #    image: byrnedo/alpine-curl
    #    container_name: alpine
    #    command: -L 'https://ipinfo.io'
    #    depends_on:
    #        - surfshark
    #    network_mode: service:surfshark
    #    restart: always


    transmission_vpn:
        image: linuxserver/transmission
        container_name: transmission_vpn
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
            - TRANSMISSION_WEB_HOME=/flood-for-transmission/
        volumes:
            - /home/pi/surfshark/transmission/config:/config             # Change this
            - /mnt/nfs-share/Transmission-VPN/Downloaded:/downloads      # Change this
            - /mnt/nfs-share/Transmission-VPN/Incoming:/watch            # Change this
        # We specify ports in the surfshark container
        #ports:
            #- 9091:9091
        network_mode: service:surfshark
        restart: unless-stopped
   
    flood:
        image: jesec/flood
        container_name: flood-ui
        command: --port 3002 --allowedpath /data/torrents
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
        volumes:
            - /home/pi/surfshark/flood/config:/config                    # Change this
            - /mnt/nfs-share/Arr_Library/torrents:/data/torrents         # Change this
        # We specify ports in the surfshark container
        #ports:
            #- 3002:3002
        network_mode: service:surfshark
        restart: unless-stopped

    qbittorrent_vpn:
        image: linuxserver/qbittorrent
        container_name: qbittorrent_vpn
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
            - WEBUI_PORT=8090
        volumes:
            - /home/pi/surfshark/qbittorrent/config:/config              # Change this
            - /mnt/nfs-share/Arr_Library/torrents:/data/torrents         # Change this
        # We specify ports in the surfshark container
        #ports:
            #- 8090:8090       
        network_mode: service:surfshark
        restart: unless-stopped

    prowlarr:
        image: linuxserver/prowlarr:develop 
        container_name: prowlarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
        volumes:
            - /home/pi/surfshark/prowlarr:/config                        # Change this
        # We specify ports in the surfshark container
        #ports:
            #- 9696:9696
        network_mode: service:surfshark
        restart: unless-stopped   
    
    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
        volumes:
            - /home/pi/surfshark/sonarr:/config                          # Change this
            - /mnt/nfs-share/Arr_Library:/data                           # Change this
        # We specify ports in the surfshark container
        #ports:
            #- 8989:8989
        network_mode: service:surfshark
        restart: unless-stopped

    radarr:
        image: linuxserver/radarr
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
        volumes:
            - /home/pi/surfshark/radarr:/config                          # Change this
            - /mnt/nfs-share/Arr_Library:/data                           # Change this
        # We specify ports in the surfshark container
        #ports:
            #- 7878:7878
        network_mode: service:surfshark
        restart: unless-stopped
        
    readarr:
        image: linuxserver/readarr:nightly
        container_name: readarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
        volumes:
            - /home/pi/surfshark/readarr:/config                         # Change this
            - /mnt/nfs-share/Arr_Library:/data                           # Change this
        # We specify ports in the surfshark container
        #ports:
            #- 8787:8787
        network_mode: service:surfshark
        restart: unless-stopped

    lidarr:
        image: linuxserver/lidarr
        container_name: lidarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
        volumes:
            - /home/pi/surfshark/lidarr:/config                          # Change this
            - /mnt/nfs-share/Arr_Library:/data                           # Change this
        # We specify ports in the surfshark container
        #ports:
            #- 8686:8686
        network_mode: service:surfshark
        restart: unless-stopped

    bazarr:
        image: linuxserver/bazarr
        container_name: bazarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
        volumes:
            - /home/pi/surfshark/bazarr:/config                          # Change this
            - /mnt/nfs-share/Arr_Library:/data                           # Change this
        # We specify ports in the surfshark container
        #ports:
            #- 6767:6767
        network_mode: service:surfshark
        restart: unless-stopped
