services:
  snapdrop:
    image: linuxserver/snapdrop
    container_name: snapdrop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago                             # Change this
    volumes:
      - /mnt/nfs-share/snapdrop/config:/config         # Change this
    ports:
      - 80:80                                          # Change this (HTTP port)
      - 443:443                                        # Change this (HTTPS port)
    restart: unless-stopped
