services:
  podgrab:
    image: akhilrex/podgrab
    container_name: podgrab
    environment:
      - CHECK_FREQUENCY=240
      - PASSWORD=<password>                             ## Uncomment to enable basic authentication, username = podgrab
    user: "1000:1000"
    volumes:
      - /mnt/nfs-share/PodGrab/config:/config
      - /mnt/nfs-share/PodGrab/data:/assets
    ports:
      - 8080:8080
    restart: unless-stopped
